export const list = [
    'Giới thiệu',
    'Bảng tin',
    'Liên hệ',
    'Sự nghiệp',
    'ByteDance',
    'Tiktok',
    'Quảng cáo',
    'Developer',
    'Transparency',
    'Tiktok Rewards',
    'Tiktok Embeds',
    'Tiktok Browse',
    'Trợ giúp',
    'An toàn',
    'Điều khoản',
    'Quyền riêng tư',
    'Hướng dẫn cộng đồng',
];
